# this package is just an example, DO NOT USE
[example]
# typically a release tag, defaults to latest
ver = "vX.Y.Z"

# remote types: github, direct (not implemented yet)
[example.remote.github]
repo = "example/example"

# platform-specific asset file names
[example.remote.github.asset]
"linux-x86_64" = "example-x86_64-unknown-linux-musl.tar.gz"
"windows-x86_64" = "example-x86_64-pc-windows-msvc.zip"

# binaries
[[example.bin]]
# name of the binary inside the asset, defaults to the name of the package
name = "example"
# name to link the binary, defaults to the bin.name
link = "example"


### packages

[btop]
[btop.remote.github]
repo = "aristocratos/btop"

[codex]
[codex.remote.github]
repo = "openai/codex"
[codex.remote.github.asset]
"linux-x86_64" = "codex-x86_64-unknown-linux-musl.tar.gz"
"windows-x86_64" = "codex-x86_64-pc-windows-msvc.exe.zip"
[[codex.bin]]
[codex.bin.name]
"linux-x86_64" = "codex-x86_64-unknown-linux-musl"
"windows-x86_64" = "codex-x86_64-pc-windows-msvc"
[codex.bin.link]
"linux-x86_64" = "codex"
"windows-x86_64" = "codex"
[[codex.bin]]
[codex.bin.name]
"windows-x86_64" = "codex-windows-sandbox-setup"
[[codex.bin]]
[codex.bin.name]
"windows-x86_64" = "codex-command-runner"

[eza]
[eza.remote.github]
repo = "eza-community/eza"

[onefetch]
[onefetch.remote.github]
repo = "o2sh/onefetch"
[onefetch.remote.github.asset]
"linux-x86_64" = "onefetch-linux.tar.gz"
"windows-x86_64" = "onefetch-win.tar.gz"

[ripgrep]
[ripgrep.remote.github]
repo = "BurntSushi/ripgrep"
[[ripgrep.bin]]
name = "rg"

[tldr]
[tldr.remote.github]
repo = "tealdeer-rs/tealdeer"

[tokei]
[tokei.remote.github]
repo = "XAMPPRocky/tokei"

[uv]
[uv.remote.github]
repo = "astral-sh/uv"
[[uv.bin]]
name = "uv"
[[uv.bin]]
name = "uvx"
