name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

env:
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Stable Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install Nightly Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo +stable clippy

      - name: Format
        run: cargo +nightly fmt -- --check
